# Copyright (c) Malong Technologies Co., Ltd.
# All rights reserved.
#
# Contact: github@malong.com
#
# This source code is licensed under the LICENSE file in the root directory of this source tree.

# Data option
CODE_PATH: /data/home/shruti/voxceleb/motion_signature/research-ms-loss-master/

DATA:
  TRAIN_IMG_SOURCE: /data/home/shruti/voxceleb/fabnet/leaders/leaders_100_train.txt
  TEST_IMG_SOURCE: /data/home/shruti/voxceleb/fabnet/leaders/leaders_100_val.txt
  TRAIN_BATCHSIZE: 50
  TEST_BATCHSIZE: 20
  NUM_WORKERS: 15 #number of data loader workers
  NUM_INSTANCES: 5 # number of instances per label in one batch

# Input option
INPUT:
  TRANSFORM: standard_scalar
  MEAN: /data/home/shruti/voxceleb/fabnet/leaders/leaders_300_mean.npy
  STD: /data/home/shruti/voxceleb/fabnet/leaders/leaders_300_std.npy
  DATA_LOADER: FabNet
  SAMPLER: random_identity_sampler
  EVAL: recall_at_k
  FRAME_LENGTH: 100 # the number of frames to consider (30 fps frame rate for leaders and 25 for voxceleb) 

# Checkpoint save dir
SAVE_DIR: /data/home/shruti/voxceleb/fabnet_ldrs_ms_T100_resnet18_iter600

# Model parameters
MODEL:
  BACKBONE:
    NAME: asym_alexnet #resnet18 #resnet50 #alexnet #vgg16_bn #asym_resnet50 #asym_alexnet
    LR_MUL: 1.0
  HEAD:
    NAME: linear_norm
    DIM: 256
    IN_CHANNEL: 1024 #1024 # alexnet # 1024 # vggnet
    LR_MUL: 1.0
    
  PRETRAIN: classification
  PRETRIANED_PATH: /data/home/shruti/voxceleb/fabnet_ldrs_clss_T100_resnet18_iter600/best_model.pth
  #PRETRAIN: resume
  #PRETRIANED_PATH: /data/home/shruti/voxceleb/fabnet_ldrs_ms_T100_asymalexnet_iter600/best_model.pth
  
SOLVER:
  MAX_ITERS: 100000
  STEPS: [100000]
  OPTIMIZER_NAME: Adam
  BASE_LR: 0.00003
  WARMUP_ITERS: 0
  WEIGHT_DECAY: 0.0005
  
VALIDATION:
  VERBOSE: 200

# Output, Loss
LOSSES:
  NAME: ms_loss
  # ms loss params
  MULTI_SIMILARITY_LOSS:
    SCALE_POS: 2.0
    SCALE_NEG: 40.0
    HARD_MINING: True