# Copyright (c) Malong Technologies Co., Ltd.
# All rights reserved.
#
# Contact: github@malong.com
#
# This source code is licensed under the LICENSE file in the root directory of this source tree.

# Data option
CODE_PATH: /data/home/shruti/voxceleb/motion_signature/research-ms-loss-master/

DATA:
  TRAIN_IMG_SOURCE: /data/home/shruti/voxceleb/fabnet/leaders/leaders_150_train.txt
  TEST_IMG_SOURCE: /data/home/shruti/voxceleb/fabnet/leaders/leaders_150_test.txt
  TRAIN_BATCHSIZE: 50
  TEST_BATCHSIZE: 256
  NUM_WORKERS: 20 #number of data loader workers
  NUM_INSTANCES: 5 # number of instances per label in one batch

# Input option
INPUT:
  TRANSFORM: standard_scalar
  MEAN: /data/home/shruti/voxceleb/fabnet/leaders/leaders_150_mean.npy
  STD: /data/home/shruti/voxceleb/fabnet/leaders/leaders_150_std.npy
  DATA_LOADER: FabNet
  SAMPLER: random_identity_sampler
  EVAL: accuracy
  FRAME_LENGTH: 150 # the number of frames to consider (30 fps frame rate for leaders and 25 for voxceleb) 

# Checkpoint save dir
SAVE_DIR: /data/home/shruti/voxceleb/mdls_ldrs_clasifictn/

# Model parameters
MODEL:
  BACKBONE:
    NAME: vgg16_bn #alexnet #
    LR_MUL: 1.0
  HEAD:
    NAME: linear_norm
    DIM: 10
    IN_CHANNEL: 2048 #1024 # alexnet 
    LR_MUL: 1.0
    
  PRETRAIN: none
  PRETRIANED_PATH: /data/home/shruti/voxceleb/mdls_ldrs_clasifictn/best_model.pth

SOLVER:
  MAX_ITERS: 200000
  STEPS: [5000]
  OPTIMIZER_NAME: Adam
  BASE_LR: 0.1
  WARMUP_ITERS: 0
  WEIGHT_DECAY: 0.0005
  
VALIDATION:
  VERBOSE: 200

# Output, Loss
LOSSES:
  NAME: ce_loss
  # ms loss params
  MULTI_SIMILARITY_LOSS:
    SCALE_POS: 2.0
    SCALE_NEG: 40.0
    HARD_MINING: True