# Copyright (c) Malong Technologies Co., Ltd.
# All rights reserved.
#
# Contact: github@malong.com
#
# This source code is licensed under the LICENSE file in the root directory of this source tree.

# Data option
CODE_PATH: /data/home/shruti/voxceleb/motion_signature/research-ms-loss-master/

DATA:
  TRAIN_IMG_SOURCE: /data/home/shruti/voxceleb/fabnet/leaders/leaders_150_train.txt
  TEST_IMG_SOURCE: /data/home/shruti/voxceleb/fabnet/leaders/leaders_150_test.txt
  TRAIN_BATCHSIZE: 50
  TEST_BATCHSIZE: 256
  NUM_WORKERS: 20 #number of data loader workers
  NUM_INSTANCES: 5 # number of instances per label in one batch

# Input option
INPUT:
  TRANSFORM: standard_scalar
  MEAN: /data/home/shruti/voxceleb/fabnet/leaders/leaders_150_mean.npy
  STD: /data/home/shruti/voxceleb/fabnet/leaders/leaders_150_std.npy
  DATA_LOADER: FabNet
  SAMPLER: random_identity_sampler
  EVAL: recall_at_k
  FRAME_LENGTH: 150 # the number of frames to consider (30 fps frame rate for leaders and 25 for voxceleb) 

# Checkpoint save dir
SAVE_DIR: /data/home/shruti/voxceleb/tmp

# Model parameters
MODEL:
  DEVICE: cuda
  BACKBONE:
    NAME: resnet50 #alexnet #vgg16_bn
    LR_MUL: 1.0
  HEAD:
    NAME: linear_norm
    DIM: 256
    IN_CHANNEL: 1024 #1024 # alexnet # 1024 # vggnet
    LR_MUL: 1.0
    
  PRETRAIN: 'resume'
  PRETRIANED_PATH: /data/home/shruti/voxceleb/mdls_ldrs_ms_resnet50_0001/best_model.pth